// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialWebApi.Models;

namespace SocialWebApi.Migrations
{
    [DbContext(typeof(SocialContext))]
    partial class SocialContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SocialWebApi.Models.SocialBoardTweets", b =>
                {
                    b.Property<int>("SocialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SocialID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedAtString")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("DateAdded");

                    b.Property<int>("FavoritedCount");

                    b.Property<int>("FollowersCount");

                    b.Property<int>("FriendsCount");

                    b.Property<string>("FullText")
                        .IsRequired();

                    b.Property<long>("Id")
                        .HasColumnName("ID");

                    b.Property<string>("IdString")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<string>("InReplyToScreenName")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("InReplyToStatusId")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<long?>("MaxId")
                        .HasColumnName("MaxID");

                    b.Property<string>("MediaType")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("MediaUrl")
                        .HasColumnName("MediaURL")
                        .IsUnicode(false);

                    b.Property<int>("Order");

                    b.Property<bool>("PossiblySensitive");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<int>("RetweetCount");

                    b.Property<string>("ScreenName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long?>("SinceId")
                        .HasColumnName("SinceID");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("SocialId");

                    b.ToTable("SocialBoardTweets");
                });
#pragma warning restore 612, 618
        }
    }
}
