// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialWebApi.Models;

namespace SocialWebApi.Migrations
{
    [DbContext(typeof(SocialContext))]
    partial class SocialContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("SocialWebApi.Models.Tweets", b =>
                {
                    b.Property<int>("SocialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SocialID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int>("FavoritedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowersCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FriendsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InReplyToScreenName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("InReplyToStatusId")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<long?>("MaxId")
                        .HasColumnName("MaxID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("MediaUrl")
                        .HasColumnName("MediaURL")
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PossiblySensitive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<int>("RetweetCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScreenName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<long?>("SinceId")
                        .HasColumnName("SinceID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SocialId");

                    b.ToTable("SocialBoardTweets");
                });
#pragma warning restore 612, 618
        }
    }
}
